apiVersion: v1
kind: Service
metadata:
  name: trivy-operator-metrics
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy-operator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  selector:
    app.kubernetes.io/name: trivy-operator
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
